import Foundation
import Testing
@testable import ChessCore

// Swift-only checks that go beyond the ported vitest suites: TS behaviours that the TS tests do
// not pin down (FEN laxness, move packing, copy semantics) and character-for-character parity of
// SAN / PGN output against fixtures generated by the TypeScript engine.

@Suite("engine port: position")
struct PositionPortTests {
    @Test("FEN parsing follows the TS: lax clocks, en-passant square, errors")
    func fenParsing() throws {
        let pos = try Position(fen: "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3")
        #expect(pos.enPassant == 20)
        #expect(pos.halfmove == 0 && pos.fullmove == 1)
        #expect(pos.fen == "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq e3 0 1")
        #expect(try Position(fen: "4k3/8/8/8/8/8/8/4K3 w - - 7 x").fullmove == 1)   // parseInt('x') || 1
        #expect(try Position(fen: "4k3/8/8/8/8/8/8/4K3 w - - x 9").halfmove == 0)   // parseInt('x') || 0
        #expect(try Position(fen: "  4k3/8/8/8/8/8/8/4K3   w  -  - 3 4 ").fen == "4k3/8/8/8/8/8/8/4K3 w - - 3 4")
        #expect(throws: FENError.invalidFEN("4k3/8/8/8/8/8/8/4K3 w -")) { try Position(fen: "4k3/8/8/8/8/8/8/4K3 w -") }
        #expect(throws: FENError.invalidPiece("x")) { try Position(fen: "4k3/8/8/8/8/8/8/4Kx2 w - - 0 1") }
    }

    @Test("squares, pieces and move packing match the TS constants")
    func typesParity() {
        #expect(squareName(0) == "a1" && squareName(7) == "h1" && squareName(56) == "a8" && squareName(63) == "h8")
        #expect(parseSquare("e4") == 28 && parseSquare("a1") == 0 && parseSquare("h8") == 63)
        #expect(parseSquare("i1") == nil && parseSquare("a9") == nil && parseSquare("a") == nil)
        #expect(fileOf(28) == 4 && rankOf(28) == 3 && squareAt(file: 4, rank: 3) == 28)
        #expect(Piece(type: .queen, color: .black).code == -5)
        #expect(Piece(type: .king, color: .white).code == 6)
        #expect(Piece(code: -3).type == .bishop && Piece(code: -3).color == .black)
        #expect(Piece.empty.type == .empty && Piece.empty.color == .black) // TS colorOf(0) === BLACK
        #expect(Piece(fenCharacter: "n") == Piece(type: .knight, color: .black))
        #expect(Piece(fenCharacter: "Q")?.fenCharacter == "Q")
        #expect(Piece(fenCharacter: "1") == nil)

        let m = Move(from: 12, to: 28, flags: .doublePush)
        #expect(m.raw == 12 | (28 << 6) | (2 << 12))
        #expect(m.from == 12 && m.to == 28 && m.flags == .doublePush && m.promotion == .empty)
        #expect(m.uci == "e2e4")
        let promo = Move(from: 52, to: 60, promotion: .queen)
        #expect(promo.raw == 52 | (60 << 6) | (5 << 16))
        #expect(promo.uci == "e7e8q")
        #expect(Move(from: 4, to: 6, flags: .castleKingside).raw == 4 | (6 << 6) | (4 << 12))
        #expect(CastlingRights.all.rawValue == 15)
        #expect(MoveFlags.enPassant.rawValue == 1 && MoveFlags.castleQueenside.rawValue == 8)
    }

    @Test("castling rights update through make/unmake")
    func castlingRightsMakeUnmake() throws {
        var pos = try Position(fen: "4k3/8/8/8/8/8/6b1/R3K2R b KQ - 0 1")
        let bxh1 = try #require(pos.generateLegalMoves().first { $0.uci == "g2h1" })
        pos.makeMove(bxh1)
        #expect(!pos.castling.contains(.whiteKingside)) // WK gone
        #expect(pos.castling.contains(.whiteQueenside)) // WQ remains
        pos.unmakeMove()
        #expect(pos.castling == [.whiteKingside, .whiteQueenside])
    }

    @Test("en passant square is set only right after a double push")
    func enPassantSquare() throws {
        var pos = try Position(fen: "4k3/2p5/8/1P6/8/8/8/4K3 b - - 0 1")
        pos.makeMove(try #require(pos.generateLegalMoves().first { $0.uci == "c7c5" }))
        #expect(pos.enPassant == parseSquare("c6"))
        let bxc6 = try #require(pos.generateLegalMoves().first { $0.uci == "b5c6" })
        #expect(bxc6.flags == .enPassant)
        pos.makeMove(try #require(pos.generateLegalMoves().first { $0.uci == "e1d1" }))
        #expect(pos.enPassant == -1)
        pos.unmakeMove()
        pos.makeMove(bxc6)
        #expect(pos.fen.split(separator: " ")[0] == "4k3/8/2P5/8/8/8/8/4K3")
        pos.unmakeMove()
        #expect(pos.fen.split(separator: " ")[0] == "4k3/8/8/1Pp5/8/8/8/4K3")
    }

    @Test("capture-promotion and underpromotion place the chosen piece")
    func promotionMakeUnmake() throws {
        var pos = try Position(fen: "3r3k/4P3/8/8/8/8/8/4K3 w - - 0 1")
        let exd8q = try #require(pos.generateLegalMoves().first { $0.uci == "e7d8q" })
        pos.makeMove(exd8q)
        #expect(pos.fen.split(separator: " ")[0] == "3Q3k/8/8/8/8/8/8/4K3")
        #expect(pos.isInCheck())
        pos.unmakeMove()
        #expect(pos.fen == "3r3k/4P3/8/8/8/8/8/4K3 w - - 0 1")

        var pos2 = try Position(fen: "4k3/6P1/8/8/8/8/8/4K3 w - - 0 1")
        let g8n = try #require(pos2.generateLegalMoves().first { $0.uci == "g7g8n" })
        #expect(g8n.promotion == .knight)
        pos2.makeMove(g8n)
        #expect(pos2.fen.split(separator: " ")[0] == "4k1N1/8/8/8/8/8/8/4K3")
    }

    @Test("checkmate and stalemate leave no legal moves")
    func noLegalMoves() throws {
        let mate = try Position(fen: "R5k1/5ppp/8/8/8/8/8/4K3 b - - 0 1")
        #expect(mate.isInCheck())
        #expect(!mate.hasLegalMoves)
        let stalemate = try Position(fen: "7k/5Q2/6K1/8/8/8/8/8 b - - 0 1")
        #expect(!stalemate.isInCheck())
        #expect(!stalemate.hasLegalMoves)
        #expect(Position().hasLegalMoves)
    }

    @Test("material scan, insufficient material and dead positions")
    func material() throws {
        let start = Position()
        #expect(start.material(of: .white).count == 15)
        #expect(start.material(of: .black).map(\.type).filter { $0 == .pawn }.count == 8)
        #expect(!start.isInsufficientMaterial)
        #expect(try Position(fen: "2b1k3/8/8/8/8/8/8/4KB2 w - - 0 1").isInsufficientMaterial) // same-coloured bishops
        #expect(try !Position(fen: "3bk3/8/8/8/8/8/8/4KB2 w - - 0 1").isInsufficientMaterial) // opposite-coloured bishops

        let bareKings = try Position(fen: "4k3/8/8/8/8/8/8/4K3 w - - 0 1")
        #expect(!bareKings.hasMatingPotential(.white))
        #expect(bareKings.isDeadPosition)
        let knightVsPawn = try Position(fen: "4k3/8/8/8/8/8/4p3/4KN2 w - - 0 1")
        #expect(knightVsPawn.hasMatingPotential(.white)) // a helping blocker exists
        #expect(!knightVsPawn.isDeadPosition)
        let loneKnight = try Position(fen: "4k3/8/8/8/8/8/8/4KN2 w - - 0 1")
        #expect(!loneKnight.hasMatingPotential(.white))
        #expect(try Position(fen: "4k3/8/8/8/8/8/8/4KNN1 w - - 0 1").hasMatingPotential(.white))
    }

    @Test("unmake restores the hash; clone drops the undo history; a plain copy keeps its own")
    func copySemantics() throws {
        var pos = try Position(fen: "r3k2r/p1ppqpb1/bn2pnp1/3PN3/1p2P3/2N2Q1p/PPPBBPPP/R3K2R w KQkq - 0 1")
        let hash = pos.hash
        for m in pos.generateLegalMoves() {
            pos.makeMove(m)
            pos.unmakeMove()
            #expect(pos.hash == hash)
        }

        var start = Position()
        start.makeMove(try #require(start.generateLegalMoves().first { $0.uci == "e2e4" }))
        var copy = start
        copy.unmakeMove()
        #expect(copy.fen == Position.startFEN)
        #expect(start.fen != Position.startFEN)
        let cloned = start.clone()
        #expect(cloned.fen == start.fen && cloned.hash == start.hash)
    }
}

@Suite("engine port: SAN")
struct SANPortTests {
    struct FixturePosition: Decodable {
        struct Entry: Decodable { let uci: String; let san: String }
        let fen: String
        let moves: [Entry]
    }

    static func fixture() throws -> [FixturePosition] {
        try JSONDecoder().decode([FixturePosition].self, from: fixtureData("san-fixtures"))
    }

    @Test("every legal move is notated exactly like the TS, in the same generation order")
    func sanMatchesFixture() throws {
        for entry in try Self.fixture() {
            let pos = try Position(fen: entry.fen)
            let legals = pos.generateLegalMoves()
            let ours = legals.map { (uci: $0.uci, san: toSAN(pos, $0, legalMoves: legals)) }
            #expect(ours.map(\.uci) == entry.moves.map(\.uci), "move order for \(entry.fen)")
            #expect(ours.map(\.san) == entry.moves.map(\.san), "SAN for \(entry.fen)")
            // toSAN without the precomputed list gives the same text
            for (m, expected) in zip(legals, entry.moves) { #expect(toSAN(pos, m) == expected.san) }
        }
    }

    @Test("fromSAN parses every fixture move as SAN and as long algebraic")
    func fromSANRoundTrip() throws {
        for entry in try Self.fixture() {
            let pos = try Position(fen: entry.fen)
            for m in entry.moves {
                #expect(fromSAN(pos, m.san)?.uci == m.uci, "SAN \(m.san) in \(entry.fen)")
                #expect(fromSAN(pos, m.uci)?.uci == m.uci, "LAN \(m.uci) in \(entry.fen)")
            }
        }
    }

    @Test("normalizeSAN strips suffix decorations and whitespace only")
    func normalize() {
        #expect(normalizeSAN("Nf3+!") == "Nf3")
        #expect(normalizeSAN("exd8=Q#") == "exd8=Q")
        #expect(normalizeSAN("O-O-O+") == "O-O-O")
        #expect(normalizeSAN(" e4 \n") == "e4")
        #expect(normalizeSAN("Qh4e1??") == "Qh4e1")
        #expect(normalizeSAN("Rxe4") == "Rxe4")
        #expect(normalizeSAN("") == "")
    }

    @Test("fromSAN: long algebraic promotion defaults to queen, wrong pieces and junk are rejected")
    func longAlgebraicDetails() throws {
        let pos = try Position(fen: "3r3k/4P3/8/8/8/8/8/4K3 w - - 0 1")
        #expect(fromSAN(pos, "e7d8")?.uci == "e7d8q")
        #expect(fromSAN(pos, "e7xd8")?.uci == "e7d8q")
        #expect(fromSAN(pos, "e7-e8=n")?.uci == "e7e8n")
        #expect(fromSAN(pos, "e7e8R")?.uci == "e7e8r")
        #expect(fromSAN(pos, "e7e8k") == nil)
        #expect(fromSAN(pos, "e7e9") == nil)
        #expect(fromSAN(pos, "e7e8q ")?.uci == "e7e8q") // trailing space trimmed
        #expect(fromSAN(pos, "e1e2q") == nil) // non-promotion with a promotion letter
        #expect(fromSAN(pos, "Ke2!?")?.uci == "e1e2")
        #expect(fromSAN(pos, "Nf3") == nil)
        #expect(fromSAN(pos, "0-0") == nil)
        let castle = try Position(fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1")
        #expect(fromSAN(castle, "0-0-0")?.uci == "e1c1")
        #expect(fromSAN(castle, "e1g1")?.flags == .castleKingside)
    }
}

@Suite("engine port: Game")
struct GamePortTests {
    @Test("history records SAN, FEN, capture, key and optional clock/think times")
    func historyEntries() throws {
        var g = Game()
        #expect(g.status == .active && g.turn == .white)
        let e4 = try #require(g.legalMoves().first { $0.uci == "e2e4" })
        #expect(g.play(e4, clockMs: 179_000, thinkMs: 1000) == "e4")
        #expect(g.playSAN("d5") == "d5")
        #expect(g.playSAN("exd5", thinkMs: 250) == "exd5")
        #expect(g.history.count == 3)
        #expect(g.history[0].clockMs == 179_000 && g.history[0].thinkMs == 1000)
        #expect(g.history[1].clockMs == nil && g.history[1].thinkMs == nil)
        #expect(g.history[2].clockMs == nil && g.history[2].thinkMs == 250)
        #expect(g.history[0].fen == "rnbqkbnr/pppppppp/8/8/4P3/8/PPPP1PPP/RNBQKBNR b KQkq - 0 1") // no ep square without an adjacent enemy pawn
        #expect(g.history[0].captured == .empty)
        #expect(g.history[2].captured == Piece(type: .pawn, color: .black))
        #expect(g.history[2].key == g.position.hashKey)
        #expect(g.history[2].move.uci == "e4d5")
        #expect(g.sanLine() == ["e4", "d5", "exd5"])
        #expect(g.uciLine() == ["e2e4", "d7d5", "e4d5"])
        #expect(g.capturedBy(.white) == [.pawn])
        #expect(g.capturedBy(.black) == [])
        #expect(g.turn == .black)
    }

    @Test("en passant captures record the pawn that was taken")
    func enPassantCaptured() throws {
        var g = try Game(fen: "4k3/2p5/8/1P6/8/8/8/4K3 b - - 0 1")
        g.playLine(["c5", "bxc6"])
        #expect(g.history[1].captured == Piece(type: .pawn, color: .black))
        #expect(g.capturedBy(.white) == [.pawn])
    }

    @Test("play rejects illegal moves and anything after the game ended")
    func playRejects() throws {
        var g = Game()
        #expect(g.play(Move(from: 12, to: 36)) == nil) // e2e5 is not legal
        #expect(g.playSAN("Nf6") == nil)
        #expect(g.history.isEmpty)
        g.playLine(["f3", "e5", "g4", "Qh4#"])
        #expect(g.status == .finished)
        #expect(g.result?.message == "Black wins by checkmate")
        #expect(g.legalMoves() == [])
        #expect(g.playSAN("Ke2") == nil)
        #expect(g.claimableDraw() == nil)
        #expect(g.claimDraw() == false)
        #expect(g.acceptDraw() == false)
        g.offerDraw(.white)
        #expect(g.drawOffer == nil)
        g.resign(.white)
        g.timeout(.white)
        #expect(g.result?.kind == .checkmate)
    }

    @Test("undo restores the position, repetition count, result and draw offer")
    func undo() {
        var g = Game()
        #expect(g.undo() == false)
        g.playLine(["Nf3", "Nf6", "Ng1", "Ng8", "Nf3", "Nf6", "Ng1", "Ng8"])
        #expect(g.repetitionCount() == 3)
        #expect(g.undo() == true)
        #expect(g.repetitionCount() == 2) // the position after 4.Ng1 was also seen after 2.Ng1
        #expect(g.claimableDraw() == nil)
        g.playSAN("Ng8")
        #expect(g.repetitionCount() == 3)
        g.claimDraw()
        #expect(g.status == .finished)
        g.undo()
        #expect(g.result == nil && g.status == .active)
        #expect(g.position.fen == "rnbqkb1r/pppppppp/5n2/8/8/8/PPPPPPPP/RNBQKBNR b KQkq - 7 4")
        g.offerDraw(.black)
        g.undo()
        #expect(g.drawOffer == nil)
        while g.undo() {}
        #expect(g.position.fen == Position.startFEN && g.history.isEmpty && g.repetitionCount() == 1)
    }

    @Test("draw offers: decline, replace, and expire with the game")
    func drawOffers() {
        var g = Game()
        g.offerDraw(.white)
        g.declineDraw()
        #expect(g.drawOffer == nil)
        #expect(g.acceptDraw() == false)
        g.offerDraw(.white)
        g.offerDraw(.black)
        #expect(g.drawOffer == .black)
        #expect(g.acceptDraw() == true)
        #expect(g.drawOffer == nil)
        #expect(g.result == GameResult(score: "1/2-1/2", kind: .agreement, winner: nil, message: "Draw by agreement"))
    }

    @Test("result messages match the TS strings")
    func resultMessages() throws {
        var w = Game(); w.resign(.black)
        #expect(w.result == GameResult(score: "1-0", kind: .resignation, winner: .white, message: "White wins by resignation"))
        var b = Game(); b.resign(.white)
        #expect(b.result?.message == "Black wins by resignation")
        var t = Game(); t.timeout(.black)
        #expect(t.result == GameResult(score: "1-0", kind: .timeout, winner: .white, message: "White wins on time"))
        var t2 = Game(); t2.timeout(.white)
        #expect(t2.result == GameResult(score: "0-1", kind: .timeout, winner: .black, message: "Black wins on time"))
        var td = try Game(fen: "4k3/8/8/8/8/8/4P3/4K3 b - - 0 1"); td.timeout(.white)
        #expect(td.result?.message == "Draw — flag fell but Black cannot checkmate")
        var td2 = try Game(fen: "4k3/4p3/8/8/8/8/8/4K3 w - - 0 1"); td2.timeout(.black)
        #expect(td2.result?.message == "Draw — flag fell but White cannot checkmate")
        var fifty = try Game(fen: "4k3/8/8/8/8/8/8/R3K3 w - - 100 80")
        #expect(fifty.claimDraw() == true)
        #expect(fifty.result?.message == "Draw by the fifty-move rule")
        var three = Game(); three.playLine(["Nf3", "Nf6", "Ng1", "Ng8", "Nf3", "Nf6", "Ng1", "Ng8"]); three.claimDraw()
        #expect(three.result?.message == "Draw by threefold repetition")
        var five = Game(); five.playLine(Array(repeating: ["Nf3", "Nf6", "Ng1", "Ng8"], count: 4).flatMap { $0 })
        #expect(five.result?.message == "Draw by fivefold repetition")
        #expect(try Game(fen: "4k3/8/8/8/8/8/8/R3K3 w - - 150 100").result?.message == "Draw by the seventy-five-move rule")
        #expect(try Game(fen: "4k3/8/8/8/8/8/8/4K3 w - - 0 1").result?.message == "Draw — insufficient material")
        #expect(try Game(fen: "7k/5Q2/6K1/8/8/8/8/8 b - - 0 1").result?.message == "Draw by stalemate")
        var mate = try Game(fen: "6k1/5ppp/8/8/8/8/8/R3K3 w - - 0 1"); mate.playSAN("Ra8#")
        #expect(mate.result?.message == "White wins by checkmate")
    }

    @Test("dead positions are already covered by the insufficient-material check")
    func deadPosition() throws {
        // isDeadPosition is material-based (neither side has mating potential), and every such
        // material set is also isInsufficientMaterial, which checkAutomaticEnd tests first. So a game
        // never ends with kind .deadPosition; the TS behaves the same (see PORTING_PLAN.md notes).
        for fen in ["4k3/8/8/8/8/8/8/1N2K3 w - - 0 1", "4kb2/8/8/8/8/8/8/2B1K3 w - - 0 1",
                    "4k3/8/8/8/8/8/8/2B1K3 w - - 0 1", "4k3/8/8/8/8/8/8/4K3 w - - 0 1"] {
            let pos = try Position(fen: fen)
            #expect(pos.isDeadPosition && pos.isInsufficientMaterial)
            #expect(try Game(fen: fen).result?.kind == .insufficient)
        }
        for fen in ["4kn2/8/8/8/8/8/8/1N2K3 w - - 0 1", "4k1b1/8/8/8/8/8/8/2B1K3 w - - 0 1",
                    "4k3/8/8/8/8/8/8/NN2K3 w - - 0 1", "4k3/8/8/8/8/8/4P3/4K3 w - - 0 1"] {
            let pos = try Position(fen: fen)
            #expect(!pos.isDeadPosition && !pos.isInsufficientMaterial)
            #expect(try Game(fen: fen).result == nil)
        }
        #expect(ResultKind.deadPosition.rawValue == "dead-position")
    }

    @Test("positionAt replays from the start FEN and never past the history")
    func positionAt() throws {
        var g = try Game(fen: "r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1")
        g.playLine(["O-O", "O-O-O", "Rae1"])
        #expect(g.positionAt(0).fen == g.startFEN)
        #expect(g.positionAt(1).fen == g.history[0].fen)
        #expect(g.positionAt(2).fen == g.history[1].fen)
        #expect(g.positionAt(3).fen == g.position.fen)
        #expect(g.positionAt(99).fen == g.position.fen)
        #expect(g.positionAt(-1).fen == g.startFEN)
        // The returned position is independent of the game.
        var p = g.positionAt(3)
        p.makeMove(try #require(p.generateLegalMoves().first))
        #expect(g.position.fen == g.history[2].fen)
    }

    @Test("a copied game is independent of the original")
    func valueSemantics() {
        var a = Game()
        a.playSAN("e4")
        var b = a
        b.playSAN("e5")
        b.offerDraw(.white)
        #expect(a.history.count == 1 && b.history.count == 2)
        #expect(a.drawOffer == nil && b.drawOffer == .white)
        #expect(a.undo() && a.history.isEmpty && b.history.count == 2)
    }

    @Test("an invalid FEN throws the TS error")
    func invalidFEN() {
        #expect(throws: FENError.invalidFEN("nope")) { try Game(fen: "nope") }
    }
}

@Suite("engine port: PGN")
struct PGNPortTests {
    @Test("default headers, order and overrides match the TS")
    func headers() throws {
        var g = Game()
        g.playLine(["e4", "e5"])
        #expect(toPGN(g) == """
            [Event "Adaptive Chess"]
            [Site "Local"]
            [Date "????.??.??"]
            [Round "-"]
            [White "White"]
            [Black "Black"]
            [Result "*"]

            1. e4 e5 *

            """)
        // Overrides keep the roster position; new keys append after Result.
        let custom = toPGN(g, headers: ["ECO": "C20", "Event": "Casual", "Date": "2026.09.26"])
        #expect(custom.hasPrefix("[Event \"Casual\"]\n[Site \"Local\"]\n[Date \"2026.09.26\"]\n[Round \"-\"]\n[White \"White\"]\n[Black \"Black\"]\n[Result \"*\"]\n[ECO \"C20\"]\n\n1. e4 e5 *\n"))
        // Object.entries: integer-like keys come first, in numeric order.
        let odd: PGNHeaders = ["Zeta": "z", "10": "ten", "2": "two", "Alpha": "a"]
        #expect(odd.entries.map(\.key) == ["2", "10", "Zeta", "Alpha"])
        #expect(odd["10"] == "ten" && odd["missing"] == nil && odd.count == 4)
        var mutable = odd
        mutable["Zeta"] = nil
        mutable["Alpha"] = "b"
        #expect(mutable.pairs.map(\.key) == ["10", "2", "Alpha"] && mutable["Alpha"] == "b")
        #expect(toPGN(g, headers: ["1": "x"]).hasPrefix("[1 \"x\"]\n[Event \"Adaptive Chess\"]"))
        // A finished game exports its score; an explicit Result header wins over it (the spread comes last).
        var mate = Game()
        mate.playLine(["f3", "e5", "g4", "Qh4#"])
        #expect(toPGN(mate).hasSuffix("[Result \"0-1\"]\n\n1. f3 e5 2. g4 Qh4# 0-1\n"))
        #expect(toPGN(mate, headers: ["Result": "*"]).contains("[Result \"*\"]\n\n1. f3 e5 2. g4 Qh4# 0-1\n"))
    }

    @Test("black-to-move starts are numbered with an ellipsis")
    func blackToMoveStart() throws {
        var g = try Game(fen: "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 5 4")
        g.playLine(["g6", "Qf3", "Nd4", "Qd3", "d5"])
        let pgn = toPGN(g)
        #expect(pgn.hasSuffix("[SetUp \"1\"]\n[FEN \"r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 5 4\"]\n\n4... g6 5. Qf3 Nd4 6. Qd3 d5 *\n"))
        let (g2, headers) = try fromPGN(pgn)
        #expect(headers["SetUp"] == "1" && headers.count == 9)
        #expect(g2.sanLine() == g.sanLine() && g2.startFEN == g.startFEN)
    }

    @Test("move text wraps at 80 columns like the TS")
    func wrapping() throws {
        var long = Game()
        long.playLine(["d4", "Nf6", "c4", "e6", "Nc3", "Bb4", "Qc2", "O-O", "a3", "Bxc3+", "Qxc3", "b6", "Bg5", "Bb7",
                       "f3", "h6", "Bh4", "d5", "e3", "Nbd7", "cxd5", "Nxd5", "Bxd8", "Nxc3", "Bh4", "Nd5", "Bf2", "c5",
                       "Bb5", "Rfd8", "Ne2", "a6", "Ba4", "b5", "Bb3", "c4", "Bc2", "Nc7", "e4", "Nf6"])
        let pgn = toPGN(long)
        // Expected text produced by the TS toPGN for the same game.
        #expect(pgn == """
            [Event "Adaptive Chess"]
            [Site "Local"]
            [Date "????.??.??"]
            [Round "-"]
            [White "White"]
            [Black "Black"]
            [Result "*"]

            1. d4 Nf6 2. c4 e6 3. Nc3 Bb4 4. Qc2 O-O 5. a3 Bxc3+ 6. Qxc3 b6 7. Bg5 Bb7 8. f3
            h6 9. Bh4 d5 10. e3 Nbd7 11. cxd5 Nxd5 12. Bxd8 Nxc3 13. Bh4 Nd5 14. Bf2 c5 15.
            Bb5 Rfd8 16. Ne2 a6 17. Ba4 b5 18. Bb3 c4 19. Bc2 Nc7 20. e4 Nf6 *

            """)
        let (g2, _) = try fromPGN(pgn)
        #expect(g2.sanLine() == long.sanLine())
    }

    @Test("import tolerates numbers glued to moves, ; comments, nested variations and stops at the result")
    func importTolerance() throws {
        let pgn = """
            [Event "Test"]
            [White "A"]
            [Black "B"]

            1.e4 e5 2.Nf3 ; the knight
            (2. f4 (2. Nc3 Nf6) exf4) 2...Nc6 3.Bb5 $6 {!} a6 1/2-1/2 4. Ba4 illegal
            """
        let (game, headers) = try fromPGN(pgn)
        #expect(game.sanLine() == ["e4", "e5", "Nf3", "Nc6", "Bb5", "a6"])
        #expect(headers.pairs.map(\.key) == ["Event", "White", "Black"])
        #expect(headers["White"] == "A" && headers["Black"] == "B" && headers["Event"] == "Test")
        #expect(game.result == nil)
        // Like the TS, a header line with trailing text is not a header: its bracket token reaches playSAN.
        let commented = pgn.replacing("[White \"A\"]", with: "[White \"A\"] ; trailing comment")
        #expect(throws: PGNError.illegalMove("[White")) { try fromPGN(commented) }
    }

    @Test("import reports the offending token and rejects bad FEN headers")
    func importErrors() throws {
        #expect(throws: PGNError.illegalMove("Nf6")) { try fromPGN("1. e4 e5 2. Nf6") }
        #expect(throws: PGNError.illegalMove("2.Kd2")) { try fromPGN("1. e4 e5 2.Kd2") }
        #expect(try fromPGN("1. e4 Nf6 e5").game.sanLine() == ["e4", "Nf6", "e5"]) // move numbers are optional
        #expect(PGNError.illegalMove("x").description == "Illegal or unparseable PGN move: x")
        #expect(throws: FENError.invalidFEN("bad")) { try fromPGN("[FEN \"bad\"]\n\n1. e4 *") }
        // A finished import carries the automatic result.
        let (mate, _) = try fromPGN("1. f3 e5 2. g4 Qh4# 0-1")
        #expect(mate.result?.kind == .checkmate)
        let (empty, headers) = try fromPGN("")
        #expect(empty.history.isEmpty && headers.isEmpty)
    }
}
