import Foundation
import Testing
@testable import ChessCore

/// tests/rules.test.ts `uciMoves`: sorted UCI strings of the legal moves.
func uciMoves(_ pos: Position) -> [String] {
    pos.generateLegalMoves().map(\.uci).sorted()
}

/// Loads a JSON fixture from Tests/ChessCoreTests/Fixtures (generated by .porting/tools/savedgame-dump.ts).
func fixtureData(_ name: String) throws -> Data {
    let url = try #require(Bundle.module.url(forResource: name, withExtension: "json", subdirectory: "Fixtures"))
    return try Data(contentsOf: url)
}

extension Game {
    /// Plays a line of SAN moves, failing the test on the first one that is rejected.
    mutating func playLine(_ sans: [String], sourceLocation: SourceLocation = #_sourceLocation) {
        for san in sans {
            #expect(playSAN(san) != nil, "rejected \(san)", sourceLocation: sourceLocation)
        }
    }
}

/// Re-serialises JSON with sorted keys so `JSON.stringify` output and `JSONEncoder` output can be compared
/// (key order and `/` escaping differ between the two; the values must not).
func canonicalJSON(_ data: Data) throws -> String {
    let object = try JSONSerialization.jsonObject(with: data)
    return String(decoding: try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys]), as: UTF8.self)
}

func canonicalJSON(_ json: String) throws -> String {
    try canonicalJSON(Data(json.utf8))
}
