import Foundation
import Testing
import ChessCore
@testable import ChessServices

/// Fixtures/services-fixtures.json is generated by .porting/tools/services-dump.ts from the TS app: the
/// puzzle catalogue, the daily puzzle for fixed dates, level/badge/offer tables and scenarios, the time
/// presets, `customTimeControl` / `formatClock` samples and the exact `JSON.stringify` blobs the TS store
/// writes under each key.
struct ServicesFixtures: Decodable, Sendable {
    struct Daily: Decodable, Sendable, CustomTestStringConvertible {
        var iso: String
        var ms: Int
        var key: String
        var hash: UInt32
        var index: Int
        var id: String
        var date: Date { Date(timeIntervalSince1970: Double(ms) / 1000) }
        var testDescription: String { iso }
    }

    struct Level: Decodable, Sendable, CustomTestStringConvertible {
        var xp: Int
        var level: Int
        var into: Int
        var needed: Int
        var testDescription: String { "xp \(xp)" }
    }

    struct BadgeInfo: Decodable, Sendable {
        var id: String
        var title: String
        var description: String
    }

    struct BadgeScenario: Decodable, Sendable, CustomTestStringConvertible {
        var name: String
        var progress: PlayerProgress
        var rating: Int
        var fresh: [String]
        var badges: [String]
        var testDescription: String { name }
    }

    struct OfferScenario: Decodable, Sendable, CustomTestStringConvertible {
        var name: String
        var weaknesses: [String: Int]
        var completedDrills: [String]
        var completedConstraints: [String]
        var lastGameWon: Bool?
        var offers: [OfferedChallenge]
        var testDescription: String { name }
    }

    struct Custom: Decodable, Sendable, CustomTestStringConvertible {
        var baseMin: Double
        var incSec: Double
        var control: TimeControl
        var testDescription: String { "\(baseMin) min + \(incSec) s" }
    }

    struct Format: Decodable, Sendable, CustomTestStringConvertible {
        var ms: Int
        var text: String
        var testDescription: String { "\(ms) ms" }
    }

    var puzzles: [Puzzle]
    var drills: [Drill]
    var constraints: [ConstraintGame]
    var daily: [Daily]
    var january: [String]
    var levels: [Level]
    var badges: [BadgeInfo]
    var badgeScenarios: [BadgeScenario]
    var offerScenarios: [OfferScenario]
    var presets: [TimeControl]
    var custom: [Custom]
    var format: [Format]
    /// `JSON.stringify` output per storage key (plus `chess.settings.partial`, `chess.progress.fresh`, `chess.progress.old`).
    var blobs: [String: String]

    /// Decoded once; parameterized tests read their arguments from here.
    static let shared: ServicesFixtures = {
        do {
            return try JSONDecoder().decode(ServicesFixtures.self, from: data())
        } catch {
            fatalError("services-fixtures.json does not decode: \(error)")
        }
    }()

    static func data() throws -> Data {
        guard let url = Bundle.module.url(forResource: "services-fixtures", withExtension: "json", subdirectory: "Fixtures") else {
            throw FixtureError.missing
        }
        return try Data(contentsOf: url)
    }

    /// The file as plain JSON objects, keyed like the file.
    static func rawObjects() throws -> [String: Any] {
        guard let raw = try JSONSerialization.jsonObject(with: data()) as? [String: Any] else { throw FixtureError.notAnObject }
        return raw
    }

    enum FixtureError: Error { case missing, notAnObject, noBlob(String) }

    func blob(_ key: String) throws -> String {
        guard let blob = blobs[key] else { throw FixtureError.noBlob(key) }
        return blob
    }
}

/// Canonical JSON text: sorted keys, no whitespace (JSONSerialization keeps `true` and `1` distinct).
func canonicalJSON(_ object: Any) throws -> String {
    let data = try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys, .fragmentsAllowed])
    return String(decoding: data, as: UTF8.self)
}

func canonicalJSON(_ data: Data) throws -> String {
    try canonicalJSON(JSONSerialization.jsonObject(with: data, options: [.fragmentsAllowed]))
}

func canonicalJSON(_ text: String) throws -> String {
    try canonicalJSON(Data(text.utf8))
}

func canonicalJSON<T: Encodable>(encoding value: T) throws -> String {
    try canonicalJSON(JSONEncoder().encode(value))
}
