import Foundation
import Testing
import ChessCore
@testable import ChessServices

/// The store records decode the JSON the TypeScript app writes and encode it back unchanged.
/// Fixtures/saved-game.json is generated by .porting/tools/savedgame-dump.ts from the TS engine,
/// following controller.ts `save()` / `archiveGame()` and worker.ts `handleAnalyze`.
@Suite("store models")
struct StoreModelsTests {
    struct Fixture: Decodable {
        let saved: SavedGame
        let savedMinimal: SavedGame
        let savedPuzzle: SavedGame
        let archive: [ArchivedGame]
    }

    static let fixtureDate = "2026.09.26"

    static func fixtureData() throws -> Data {
        let url = try #require(Bundle.module.url(forResource: "saved-game", withExtension: "json", subdirectory: "Fixtures"))
        return try Data(contentsOf: url)
    }

    /// The fixture's raw JSON objects, keyed like the file.
    static func rawObjects() throws -> [String: Any] {
        try #require(JSONSerialization.jsonObject(with: fixtureData()) as? [String: Any])
    }

    /// Canonical bytes: sorted keys, no whitespace. JSONSerialization keeps `true` and `1` distinct.
    static func canonical(_ object: Any) throws -> String {
        let data = try JSONSerialization.data(withJSONObject: object, options: [.sortedKeys])
        return String(decoding: data, as: UTF8.self)
    }

    static func canonical(_ data: Data) throws -> String {
        try canonical(JSONSerialization.jsonObject(with: data))
    }

    static func roundTrip<T: Codable>(_ type: T.Type, _ object: Any, sourceLocation: SourceLocation = #_sourceLocation) throws -> T {
        let data = try JSONSerialization.data(withJSONObject: object)
        let decoded = try JSONDecoder().decode(T.self, from: data)
        let encoded = try JSONEncoder().encode(decoded)
        #expect(try canonical(encoded) == canonical(object), sourceLocation: sourceLocation)
        // Decoding our own output gives an equal value.
        #expect(try JSONDecoder().decode(T.self, from: encoded) as? AnyHashable == decoded as? AnyHashable, sourceLocation: sourceLocation)
        return decoded
    }

    @Test("saved games decode and re-encode to the same JSON")
    func savedGamesRoundTrip() throws {
        let raw = try Self.rawObjects()
        for key in ["saved", "savedMinimal", "savedPuzzle"] {
            let object = try #require(raw[key])
            _ = try Self.roundTrip(SavedGame.self, object)
        }
    }

    @Test("archived games decode and re-encode to the same JSON")
    func archivedGamesRoundTrip() throws {
        let raw = try Self.rawObjects()
        let archive = try #require(raw["archive"] as? [Any])
        #expect(archive.count == 3)
        for object in archive { _ = try Self.roundTrip(ArchivedGame.self, object) }
        _ = try Self.roundTrip([ArchivedGame].self, archive)
    }

    @Test("decoded values match the TS records")
    func decodedValues() throws {
        let f = try JSONDecoder().decode(Fixture.self, from: Self.fixtureData())

        #expect(f.saved.mode == .ai && f.saved.playerColor == .white && f.saved.difficulty == .match)
        #expect(f.saved.startFen == Position.startFEN)
        #expect(f.saved.uciMoves.count == 18 && f.saved.thinkMs.count == 18)
        #expect(f.saved.uciMoves.prefix(3) == ["e2e4", "e7e5", "g1f3"] && f.saved.thinkMs.prefix(2) == [1200, 461])
        #expect(f.saved.timeControl == TimeControl(name: "Blitz 3+2", baseMs: 180_000, incrementMs: 2000))
        #expect(f.saved.clockRemaining == ClockRemaining(white: 171_250, black: 168_900))
        #expect(f.saved.clockRemaining?[.white] == 171_250 && f.saved.clockRemaining?[.black] == 168_900)
        #expect(f.saved.timerOn && f.saved.hintsLeft == 2 && f.saved.challengeId == nil)
        #expect(f.saved.adaptationNotes == ["Your style is still balanced — I played neutrally while I learn your patterns."])
        #expect(f.saved.aiSkill == 2.5 && f.saved.aiElo == 800 && f.saved.savedAt == 1_790_380_800_000)

        #expect(f.savedMinimal.mode == .pvp && f.savedMinimal.difficulty == .learn)
        #expect(f.savedMinimal.timeControl == nil && f.savedMinimal.clockRemaining == nil && f.savedMinimal.challengeId == nil)
        #expect(!f.savedMinimal.timerOn && f.savedMinimal.hintsLeft == 0 && f.savedMinimal.adaptationNotes.isEmpty)
        #expect(f.savedMinimal.aiSkill == 20 && f.savedMinimal.aiElo == 2200)

        #expect(f.savedPuzzle.mode == .puzzle && f.savedPuzzle.playerColor == .black && f.savedPuzzle.difficulty == .challenge)
        #expect(f.savedPuzzle.timeControl == TimeControl(name: "Handicap", baseMs: 300_000, incrementMs: 0, whiteBaseMs: 120_000, blackBaseMs: 300_000))
        #expect(f.savedPuzzle.challengeId == "mate-back-rank-1" && f.savedPuzzle.aiSkill == 13.75)
        #expect(f.savedPuzzle.uciMoves.isEmpty && f.savedPuzzle.thinkMs.isEmpty)

        let analysed = f.archive[0]
        #expect(analysed.mode == .ai && analysed.playerColor == .white && analysed.aiElo == 1420)
        #expect(analysed.result == "White wins by checkmate" && analysed.score == "1-0")
        #expect(analysed.date == 1_790_380_800_003)
        let analysis = try #require(analysed.analysis)
        #expect(analysis.count == 7)
        #expect(analysis[0] == AnalyzedMove(uci: "e2e4", evalAfter: -18, evalBefore: 0, bestUci: "b1c3", judgment: .good, cpLoss: 18))
        #expect(analysis.last?.uci == "h5f7" && analysis.last?.cpLoss == 0 && analysis.last?.judgment == .best)
        #expect(analysed.adaptationNotes.count == 1)

        let pvp = f.archive[1]
        #expect(pvp.mode == .pvp && pvp.aiElo == nil && pvp.analysis == nil)
        #expect(pvp.result == "White wins by resignation" && pvp.score == "1-0" && pvp.uciMoves.count == 18)

        let drill = f.archive[2]
        #expect(drill.mode == .drill && drill.playerColor == .black && drill.aiElo == 1100)
        #expect(drill.analysis == [] && drill.result == "" && drill.score == "*")
        #expect(drill.startFen == "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR b KQkq - 5 4")
    }

    @Test("archived PGN is exactly what the Swift exporter produces for the same game")
    func archivedPGNParity() throws {
        let f = try JSONDecoder().decode(Fixture.self, from: Self.fixtureData())
        for entry in f.archive {
            var game = try Game(fen: entry.startFen)
            for uci in entry.uciMoves {
                let move = try #require(game.legalMoves().first { $0.uci == uci }, "\(uci) in \(entry.pgn)")
                #expect(game.play(move) != nil)
            }
            if game.result == nil, entry.result.hasSuffix("wins by resignation") {
                game.resign(entry.score == "1-0" ? .black : .white)
            }
            #expect(game.result?.message ?? "" == entry.result)
            #expect(game.result?.score ?? "*" == entry.score)
            // controller.ts archiveGame() headers
            let aiName = "AI (\(entry.aiElo ?? 0))"
            let headers: PGNHeaders = [
                "White": entry.mode == .pvp ? "White" : entry.playerColor == .white ? "You" : aiName,
                "Black": entry.mode == .pvp ? "Black" : entry.playerColor == .black ? "You" : aiName,
                "Date": Self.fixtureDate,
            ]
            #expect(toPGN(game, headers: headers) == entry.pgn)
            let (imported, importedHeaders) = try fromPGN(entry.pgn)
            #expect(imported.sanLine() == game.sanLine())
            #expect(imported.position.fen == game.position.fen)
            #expect(importedHeaders["Result"] == entry.score && importedHeaders["Date"] == Self.fixtureDate)
        }
    }

    @Test("nullable fields encode as explicit null and undefined ones are omitted")
    func nullsAndOmissions() throws {
        let saved = SavedGame(mode: .pvp, startFen: Position.startFEN, uciMoves: [], thinkMs: [], playerColor: .black,
                              difficulty: .learn, timeControl: nil, clockRemaining: nil, timerOn: false, hintsLeft: 0,
                              challengeId: nil, adaptationNotes: [], aiSkill: 20, aiElo: 2200, savedAt: 1)
        let savedJSON = try Self.canonical(JSONEncoder().encode(saved))
        #expect(savedJSON.contains("\"timeControl\":null"))
        #expect(savedJSON.contains("\"clockRemaining\":null"))
        #expect(savedJSON.contains("\"challengeId\":null"))
        #expect(savedJSON.contains("\"playerColor\":\"b\""))
        #expect(savedJSON.contains("\"timerOn\":false"))
        // What the TS app writes for the same record (canonicalised the same way; JSONSerialization escapes "/").
        let expected = """
            {"mode":"pvp","startFen":"\(Position.startFEN)","uciMoves":[],"thinkMs":[],"playerColor":"b","difficulty":"learn",\
            "timeControl":null,"clockRemaining":null,"timerOn":false,"hintsLeft":0,"challengeId":null,"adaptationNotes":[],\
            "aiSkill":20,"aiElo":2200,"savedAt":1}
            """
        #expect(savedJSON == (try Self.canonical(Data(expected.utf8))))

        let tc = try Self.canonical(JSONEncoder().encode(TimeControl(name: "Bullet 1+0", baseMs: 60_000, incrementMs: 0)))
        #expect(tc == "{\"baseMs\":60000,\"incrementMs\":0,\"name\":\"Bullet 1+0\"}")
        let handicap = try Self.canonical(JSONEncoder().encode(TimeControl(name: "H", baseMs: 1, incrementMs: 2, whiteBaseMs: 3)))
        #expect(handicap == "{\"baseMs\":1,\"incrementMs\":2,\"name\":\"H\",\"whiteBaseMs\":3}")

        let archived = ArchivedGame(pgn: "*", mode: .ai, playerColor: .white, result: "", score: "*", aiElo: nil, date: 2,
                                    analysis: nil, adaptationNotes: [], startFen: Position.startFEN, uciMoves: [])
        let archivedJSON = try Self.canonical(JSONEncoder().encode(archived))
        #expect(archivedJSON.contains("\"aiElo\":null") && archivedJSON.contains("\"analysis\":null"))
        #expect(archivedJSON.contains("\"playerColor\":\"w\""))

        let clock = try Self.canonical(JSONEncoder().encode(ClockRemaining(white: 5, black: 6)))
        #expect(clock == "[5,6]")
        #expect(throws: (any Error).self) { try JSONDecoder().decode(ClockRemaining.self, from: Data("[5]".utf8)) }
        #expect(throws: (any Error).self) { try JSONDecoder().decode(SavedGame.self, from: Data("{}".utf8)) }
        #expect(throws: (any Error).self) { try JSONDecoder().decode(PlayerColorCode.self, from: Data("\"x\"".utf8)) }
    }

    @Test("enum raw values are the TS string unions")
    func enumStrings() {
        #expect(GameMode.allCases.map(\.rawValue) == ["pvp", "ai", "puzzle", "drill", "constraint"])
        #expect(DifficultyMode.allCases.map(\.rawValue) == ["learn", "match", "challenge"])
        #expect(Judgment.allCases.map(\.rawValue) == ["best", "good", "inaccuracy", "mistake", "blunder"])
        #expect(ResultKind.allCases.map(\.rawValue) == ["checkmate", "stalemate", "resignation", "timeout", "timeout-draw",
                                                        "agreement", "threefold", "fivefold", "fifty-move", "seventy-five-move",
                                                        "insufficient", "dead-position", "aborted"])
        #expect(PlayerColorCode(.white).rawValue == "w" && PlayerColorCode(.black).rawValue == "b")
        #expect(PlayerColorCode.w.color == .white && PlayerColorCode.b.color == .black)
    }
}
